name: .NET

on:
  push:   
    paths:
      - 'MTCRequestBot/**'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration 'Release'
      
    - name: Set PR build number (PR)
      id: PRNUMBER
      if: ${{ github.event_name == 'pull_request' }}
      uses: kkak10/pr-number-action@v1.3
    
    - name: Set Test Title (PR)
      if: ${{ github.event_name == 'pull_request'}}
      run: |
        echo "title=Test Run for PR #${{steps.PRNUMBER.outputs.pr}} (${{ github.run_number }})" >> $GITHUB_ENV
        echo "file_name=TestReports.${{steps.PRNUMBER.outputs.pr}}.${{ github.run_number }}.md" >> $GITHUB_ENV
    
    - name: Set Test Title (PUSH)
      if: ${{github.event_name != 'pull_request'}}
      run: |
        echo "title=TestRun${{github.run_number}}" >> $GITHUB_ENV
        echo "file_name=TestReport.${{github.run_number}}.md" >> $GITHUB_ENV
    
    - name: Test
      run: dotnet test --no-build --no-restore --configuration 'Release' --verbosity normal
