# This is a basic workflow to help you get started with Actions

name: LUIS-CI

# Triggers the workflow on push to the master branch, and only for changes to lu or json files.
# events but only for the master branch
on:
  push:
    branches:
      - master
    paths: 
      - 'MTCBot.AI/luis-app/*.lu'
      - 'MTCBot.AI/luis-app/tests/*.json'
env:
  LUIS_MASTER_APP_NAME: LUISMTCBot-master
  IS_PRIVATE_REPOSITORY: true
  # Set the path to the lu file for your LUIS app
  LU_FILE: MTCBot.AI/luis-app/model.lu
  # Set the path to the file for your unit tests
  UNIT_TEST_FILE: MTCBot.AI/luis-app/tests/unittests.json
  # Set the path to the file for your unit tests
  QUALITY_TEST_FILE: MTCBot.AI/luis-app/tests/verificationtests.json

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
