# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
name: LUIS-PR

# Trigger the workflow on pull request, and only for changes to lu or json files
on:
  pull_request:
    paths:
      - 'MTCBot.AI/luis-app/*.lu'
      - 'MTCBot.AI/luis-app/tests/*.json'

env:
  # Set the name of the master LUIS app
  LUIS_MASTER_APP_NAME: MTCBot-PR  

  # Set the path to the lu file for your LUIS app
  LU_FILE: MTCBot.AI/luis-app/model.lu
  # Set the path to the file for your unit tests
  UNIT_TEST_FILE: MTCBot.AI/luis-app/tests/unittests.json

jobs:
  build:
    name: Build and Test LUIS model (PR)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get LUIS authoring key
      run: |
        keya=$(az cognitiveservices account keys list --name ${{ secrets.AZURE_LUIS_AUTHORING_RESOURCE_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --query "key1" | xargs)
        echo "LUISAuthoringKey=$keya" >> $GITHUB_ENV
        echo "::add-mask::$keya"

    - name: Get LUIS prediction key
      run: |
        keyp=$(az cognitiveservices account keys list --name ${{ secrets.AZURE_LUIS_PREDICTION_RESOURCE_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --query "key1" | xargs)
        echo "LUISPredictionKey=$keyp" >> $GITHUB_ENV
        echo $LUISPredictionKey
        #echo "::add-mask::$keyp"


    - name: Get LUIS authoring endpoint
      run: |
        az cognitiveservices account show --name ${{ secrets.AZURE_LUIS_AUTHORING_RESOURCE_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --query "properties.endpoint" | \
        xargs -I {} echo "LUISAuthoringEndpoint={}" >> $GITHUB_ENV

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install botframework-cli
      run: npm i -g @microsoft/botframework-cli@4.11.1

    - name: Bypass botframework-cli telemetry prompts, enable telemetry collection - set to false to disable telemetry collection
      run: echo "BF_CLI_TELEMETRY=true" >> $GITHUB_ENV

    - name: Ludown to LUIS model
      run: bf luis:convert -i $LU_FILE -o ./model.json --name 'LUIS PR pipeline - ${{ github.run_id }}' --versionid 0.1

    # When doing a gate check on PRs, we build a new LUIS application for testing that is later deleted
    - name: Create PR check LUIS application
      run: |
        response=$(bf luis:application:import --endpoint $LUISAuthoringEndpoint --subscriptionKey $LUISAuthoringKey  --in model.json --json)
        status=$(echo "$response" | jq '.Status' | xargs)
        if [ "$status" == "Success" ]
        then
          appId=$(echo "$response" | jq '.id' | tr -d '\\"')
          echo "LUISAppId=$appId" >> $GITHUB_ENV
        else
          exit 1
        fi

    - name: Train luis
      run: bf luis:train:run --appId $LUISAppId --versionId 0.1 --endpoint $LUISAuthoringEndpoint --subscriptionKey $LUISAuthoringKey

    - name: Wait for train
      run: |
        while true
        do
          status=`bf luis:version:list --appId $LUISAppId --endpoint $LUISAuthoringEndpoint --subscriptionKey $LUISAuthoringKey |  jq '.[] | select(.version == "0.1") | .trainingStatus' | xargs`
          if [ "$status" == "Trained" ]
          then
            break
          elif [ "$status" == "Failed" ]
          then
            exit 1
          fi
          echo 'sleep 10'
          sleep 10
        done

    - name: Publish luis
      run: bf luis:application:publish --appId $LUISAppId --versionId 0.1 --endpoint $LUISAuthoringEndpoint --subscriptionKey $LUISAuthoringKey

    - name: Install dotnet-nlu
      run: dotnet tool install -g dotnet-nlu --version 0.7.5

    - name: Add dotnet Tools to Path
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Get Azure subscriptionId
      run: |
        az account show --query 'id' | \
        xargs -I {} echo "AzureSubscriptionId={}" >> $GITHUB_ENV

    - name: Assign LUIS Azure Prediction resource to application
      shell: pwsh
      run: |
        bf luis:application:assignazureaccount --azureSubscriptionId $env:AzureSubscriptionId --appId $env:LUISAppId --accountName $env:luisPredictionResourceName --subscriptionKey $env:LUISAuthoringKey --endpoint $env:LUISAuthoringEndpoint --resourceGroup $env:azureResourceGroup --armToken $(az account get-access-token --query accessToken -o tsv)
      env:
        luisPredictionResourceName: ${{ secrets.AZURE_LUIS_PREDICTION_RESOURCE_NAME }}
        azureResourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}

    - name: Test Luis model
      run: dotnet nlu test -s luisV3 -u $UNIT_TEST_FILE -o results.json
      env:
        luisAppId: ${{ env.LUISAppId }}
        luisVersionId: 0.1
        luisEndpointKey: ${{ env.LUISPredictionKey }}
        luisPredictionResourceName: ${{ secrets.AZURE_LUIS_PREDICTION_RESOURCE_NAME }}
        luisIsStaging: false
        
    - name: Set PR Build Number
      id: PRNUMBER
      if: ${{ github.event_name == 'pull_request' }}
      uses: kkak10/pr-number-action@v1.3

    - name: Analyze Unit test results
      id: analyze_unit_tests
      run: |
        result=$(dotnet nlu compare -e $UNIT_TEST_FILE -a results.json --unit-test --output-folder unittest)
        result="${result//'%'/'%25'} 【7,6 m】"
        result="${result//$'\n'/'%0A'}"
        result="${result//$'\r'/'%0D'}"
        echo "::set-output name=unittestresults::$result"      
    - uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        header: test
        message: |
          ```
          ${{ steps.analyze_unit_tests.outputs.unittestresults }}
          ```     
    
        
    - name: Upload Unit Test Results as a Build Artifact
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: UnitTestResult${{steps.PRNUMBER.outputs.pr}}
        path: unittest/TestResult.xml

    # Delete the LUIS app again if we are executing as gate check on a PR
    - name: Delete luis test target app
      if: always()
      run:  bf luis:application:delete --appId $LUISAppId --endpoint $LUISAuthoringEndpoint --subscriptionKey $LUISAuthoringKey --force
